# Creates a deployment set 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping 
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/shipping:4.0.1
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef: 
              name: shipping-configmap
--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap 
data:
     CART_ENDPOINT: cart-svc 
     DB_HOST: mysql-dev.roboshop.internal
# Ingress Resource

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipping-ingress
spec:
   rules:
     - http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: shipping-svc
              port:
                number: 8080
   ingressClassName: nginx